name: Next Gen AI Power Trader App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build React frontend and backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Upload backend as artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend
        path: backend

    - name: Upload frontend as artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend
        path: backend

    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend
        path: frontend

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/next-gen-power-trader-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/next-gen-power-trader-app:latest

    - name: Deploy to Render.com
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}